# -*- coding: utf-8 -*-
"""Praktikum_ZainAmmarFalih.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16R8dc9LtQ9THrxsmBPL98MygG99ztlFk

Jurnal Praktikum 1
Nama : Zain Ammar Falih
Kelas : SIKJ-24-01
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
path = '/content/Diabetes_dataset_2026.csv'

# Load dataset
df = pd.read_csv('Diabetes_dataset_2026.csv', sep=';')

# Tampilkan 5 data teratas
df.head(5)

df.info()

df['BMI'].value_counts()

df.describe()

# Missing values
missing = df.isnull().sum()

print("Missing Values:\n", missing)

# Data duplikat
duplicates = df.duplicated().sum()

print("\nJumlah Duplikat:", duplicates)

corr_matrix = df.corr(numeric_only=True)

plt.figure(figsize=(12,8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

df.hist(figsize=(15,10))
plt.tight_layout()
plt.show()

df.fillna(df.median(numeric_only=True), inplace=True)

df.describe()

def fix_health_data(row):
    for col in ['HbA1c', 'Glucose', 'BloodPressure', 'LDL', 'HDL', 'Triglycerides', 'WaistCircumference', 'HipCircumference']:
        if col in row and row[col] > 300:
            row[col] = round(row[col] / 10, 1)

    if 'BMI' in row and row['BMI'] > 100:
        row['BMI'] = round(row['BMI'] / 100, 2)

    if 'WHR' in row and row['WHR'] > 2:
        row['WHR'] = round(row['WHR'] / 100, 2)

    return row

df = df.apply(fix_health_data, axis=1)
df.head()

cols = ['BMI', 'Glucose', 'BloodPressure', 'HbA1c']

for col in cols:
    df[col] = df[col].replace(0, np.nan)
    df[col].fillna(df[col].median(), inplace=True)

# Verifikasi
df.head()

df[cols].agg(['mean', 'min', 'max'])

# Pisahkan numerik
num_cols = df.select_dtypes(include=np.number).columns
num_cols = num_cols.drop(['Outcome'], errors='ignore')

# Hitung outlier sebelum
outlier_before = {}

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_before[col] = ((df[col] < lower) | (df[col] > upper)).sum()

print("Outlier Sebelum:", outlier_before)

# Capping
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

# Hitung setelah
outlier_after = {}

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_after[col] = ((df[col] < lower) | (df[col] > upper)).sum()

print("\nOutlier Sesudah:", outlier_after)

df['BMI'].value_counts()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = df.select_dtypes(include=np.number).columns

df[num_cols] = scaler.fit_transform(df[num_cols])

df.head()

"""**Praktikum 2**"""

#Soal 1

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df_numeric = df.select_dtypes(include=['number']).dropna()

X = df_numeric.drop(columns=['Glucose'])
y = df_numeric['Glucose']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
    )

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

#Soal 2

from sklearn.metrics import mean_squared_error, r2_score

# a. Prediksi nilai y_pred
y_pred = lr_model.predict(X_test)

# b & c. Hitung MSE dan R-squared
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# d. Tampilkan hasil
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 Score): {r2}")

#Soal 3

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
# Membuat scatter plot
plt.scatter(y_test, y_pred, alpha=0.6, color='#2ecc71')

# Membuat garis diagonal y=x sebagai referensi
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)

plt.xlabel('Nilai Aktual (Glucose)')
plt.ylabel('Nilai Prediksi (Glucose)')
plt.title('Grafik Perbandingan: Nilai Aktual vs Prediksi Glucose')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

#Soal 4
from sklearn.cluster import KMeans

X = df_numeric.drop(columns=['Outcome'])
inertia = []
K_range = range(1, 11)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X) # X_scaled adalah data yang sudah dinormalisasi
    inertia.append(km.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(K_range, inertia, marker='o', linestyle='-', color='#3498db')
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('Inertia / Distortion')
plt.title('Elbow Method untuk Mencari k Optimal')
plt.grid(True)
plt.show()

#Soal 5

from sklearn.metrics import silhouette_score

sil_scores = {}
# Menguji k dari 2 sampai 5
for k in range(2, 6):
    km_sil = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km_sil.fit_predict(X)
    score = silhouette_score(X, labels)
    sil_scores[k] = score
    print(f"Silhouette Score untuk k={k}: {score}")

best_k = max(sil_scores, key=sil_scores.get)
print(f"Jumlah cluster terbaik adalah k={best_k}")

#Soal 6

from sklearn.decomposition import PCA

# Reduksi menjadi 2 dimensi agar bisa divisualisasikan
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Menjalankan K-Means pada data yang sudah di-scale
final_km = KMeans(n_clusters=2, random_state=42)
final_labels = final_km.fit_predict(X)

#Soal 7

from sklearn.decomposition import PCA
import seaborn as sns

# Reduksi dimensi menjadi 2D
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Latih K-Means dengan k terbaik (misal k=2)
final_km = KMeans(n_clusters=2, random_state=42, n_init=10)
final_labels = final_km.fit_predict(X)
centroids_pca = pca.transform(final_km.cluster_centers_)

plt.figure(figsize=(10, 7))
# Visualisasi sebaran cluster
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=final_labels, cmap='viridis', alpha=0.5)

# Menandai posisi Centroids
plt.scatter(centroids_pca[:, 0], centroids_pca[:, 1], s=200, c='red', marker='X', label='Centroids')

plt.colorbar(scatter, label='Cluster ID')
plt.title('Visualisasi Cluster K-Means dengan PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend()
plt.show()

"""**Praktikum 3**"""

# 1) Impor fungsi yang diperlukan
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 2) Tentukan X dan y
X_clf = df_numeric.drop(columns=['Outcome'])
y_clf = df_numeric['Outcome']

# 3) Bagi dataset (70% training, 30% testing)
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
    X_clf, y_clf, test_size=0.3, random_state=42
)

# 4) Standarisasi Data
scaler_clf = StandardScaler()
# Fitting HANYA pada data training untuk menghindari data leakage
X_train_scaled = scaler_clf.fit_transform(X_train_clf)
# Transformasi pada data testing
X_test_scaled = scaler_clf.transform(X_test_clf)

# 1) Impor algoritma GaussianNB
from sklearn.naive_bayes import GaussianNB

# 2) Inisialisasi model
nb_model = GaussianNB()

# 3) Latih model dengan data training yang distandarisasi
# Mengonversi y_train_clf menjadi label integer diskrit (0 atau 1)
# karena StandardScaler sebelumnya mengonversi label ini menjadi float.
nb_model.fit(X_train_scaled, y_train_clf.round().astype(int))

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Lakukan prediksi
y_pred_clf = nb_model.predict(X_test_scaled)

# Konversi target dan prediksi ke integer diskrit (0 atau 1)
# karena data sebelumnya telah melewati StandardScaler
y_test_clf_disc = y_test_clf.round().astype(int)
y_pred_clf_disc = y_pred_clf.round().astype(int)

# a) Hitung metrik evaluasi
print(f"Accuracy: {accuracy_score(y_test_clf_disc, y_pred_clf_disc):.4f}")
print(f"Precision: {precision_score(y_test_clf_disc, y_pred_clf_disc):.4f}")
print(f"Recall: {recall_score(y_test_clf_disc, y_pred_clf_disc):.4f}")
print(f"F1-Score: {f1_score(y_test_clf_disc, y_pred_clf_disc):.4f}")

# b) Tampilkan Confusion Matrix & Classification Report
print("\nConfusion Matrix:\n", confusion_matrix(y_test_clf_disc, y_pred_clf_disc))
print("\nClassification Report:\n", classification_report(y_test_clf_disc, y_pred_clf_disc))

# 1) Impor library untuk penanganan data imbalance (SMOTE)
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns

# 2) Tampilkan distribusi jumlah kelas sebelum SMOTE
print("Distribusi kelas (Outcome) pada data training sebelum SMOTE:")
print(y_train_clf.value_counts())

# 1) Terapkan SMOTE pada data training yang telah di-scale
smote = SMOTE(random_state=42)
# Konversi y_train_clf ke integer karena StandardScaler mengubahnya menjadi float
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train_clf.round().astype(int))

# 2) Tampilkan kembali distribusi kelas setelah SMOTE
print("Distribusi kelas (Outcome) pada data training setelah SMOTE:")
print(pd.Series(y_train_smote).value_counts())

# 1) Bangun dan latih ulang model dengan data SMOTE
nb_smote = GaussianNB()
nb_smote.fit(X_train_smote, y_train_smote)

# 2) Lakukan prediksi dengan model baru
y_pred_smote = nb_smote.predict(X_test_scaled)

# 3) Evaluasi dengan classification report
# Mengonversi y_test_clf menjadi integer agar sesuai dengan tipe label prediksi
y_test_clf_disc = y_test_clf.round().astype(int)

print("Classification Report (Model Naive Bayes + SMOTE):\n")
print(classification_report(y_test_clf_disc, y_pred_smote))

# 1) Visualisasi perbandingan Confusion Matrix
fig, ax = plt.subplots(1, 2, figsize=(12, 5))

# Menggunakan y_test_clf_disc (integer) alih-alih y_test_clf (float)
cm_before = confusion_matrix(y_test_clf_disc, y_pred_clf_disc)
cm_after = confusion_matrix(y_test_clf_disc, y_pred_smote)

sns.heatmap(cm_before, annot=True, fmt='d', cmap='Blues', ax=ax[0])
ax[0].set_title('Confusion Matrix (Sebelum SMOTE)')
ax[0].set_xlabel('Prediksi')
ax[0].set_ylabel('Aktual')

sns.heatmap(cm_after, annot=True, fmt='d', cmap='Greens', ax=ax[1])
ax[1].set_title('Confusion Matrix (Setelah SMOTE)')
ax[1].set_xlabel('Prediksi')
ax[1].set_ylabel('Aktual')

plt.tight_layout()
plt.show()

import pickle
from sklearn.preprocessing import StandardScaler

# 1) Simpan model Regresi (dari tugas part 1) dan scalernya
with open('linear_regression_model.pkl', 'wb') as f:
    pickle.dump(lr_model, f)

# Buat scaler baru khusus untuk fitur input model regresi linier (X_train)
# X_train memiliki 16 fitur (df_numeric asli dikurangi 'Glucose')
lr_feature_scaler = StandardScaler()
lr_feature_scaler.fit(X_train) # Fit pada fitur training untuk regresi linier

with open('scaler_lr.pkl', 'wb') as f:
    pickle.dump(lr_feature_scaler, f) # Simpan scaler baru ini

# 2) Simpan model Klasifikasi (Naive Bayes + SMOTE) dan scalernya
with open('naive_bayes_model.pkl', 'wb') as f:
    pickle.dump(nb_smote, f)

# scaler_clf sudah sesuai karena dilatih pada X_train_clf (16 fitur)
with open('scaler_nb.pkl', 'wb') as f:
    pickle.dump(scaler_clf, f)

# 3) Pesan Konfirmasi
print("Seluruh model dan scaler telah berhasil di-export dan disimpan (format .pkl)!")

import os

streamlit_app_code = '''
import streamlit as st
import pickle
import numpy as np

# Konfigurasi Halaman
st.set_page_config(
    page_title="Dashboard RS Sehat Sentosa",
    page_icon=":material/local_hospital:",
    layout="wide"
)

# Load model dan scaler
@st.cache_resource
def load_models():
    try:
        lr_model = pickle.load(open('linear_regression_model.pkl', 'rb'))
        scaler_lr = pickle.load(open('scaler_lr.pkl', 'rb'))
        nb_model = pickle.load(open('naive_bayes_model.pkl', 'rb'))
        scaler_nb = pickle.load(open('scaler_nb.pkl', 'rb'))
        return lr_model, scaler_lr, nb_model, scaler_nb
    except FileNotFoundError:
        st.error(":material/warning: File Model (.pkl) tidak ditemukan. Pastikan file berada di folder yang sama!")
        st.stop()

lr_model, scaler_lr, nb_model, scaler_nb = load_models()

# Sidebar Navigation
st.sidebar.title(":material/dashboard: Navigasi Utama")
st.sidebar.markdown("Silakan pilih menu layanan:")
page = st.sidebar.radio("Menu", [
    ":material/home: Beranda",
    ":material/water_drop: Prediksi Glukosa (Regresi)",
    ":material/stethoscope: Klasifikasi Diabetes"
])
st.sidebar.markdown("---")
st.sidebar.info(":material/info: Dashboard analitik ini dirancang khusus untuk tim medis RS Sehat Sentosa guna deteksi dini risiko diabetes.")

# ================= BERANDA =================
if page == ":material/home: Beranda":
    st.title(":material/local_hospital: Sistem Cerdas Deteksi Dini Diabetes")
    st.markdown("### Selamat Datang di Dashboard Rumah Sakit Sehat Sentosa")
    st.write("""
    Aplikasi ini ditenagai oleh model **Machine Learning** terintegrasi untuk membantu tenaga medis:

    1. **Prediksi Glukosa:** Mengestimasi kadar glukosa darah pasien secara kuantitatif berdasarkan profil klinis (Algoritma *Linear Regression*).
    2. **Klasifikasi Risiko:** Memprediksi apakah pasien berisiko tinggi terkena diabetes atau tidak (Algoritma *Naive Bayes + SMOTE*).

    :material/arrow_back: *Silakan pilih menu pada panel navigasi di sebelah kiri untuk mulai menggunakan fitur.*
    """)

# ================= HALAMAN PREDIKSI GLUKOSA =================
elif page == ":material/water_drop: Prediksi Glukosa (Regresi)":
    st.title(":material/water_drop: Prediksi Kadar Glukosa Darah")
    st.markdown("Geser slider di bawah ini untuk memasukkan data klinis pasien dan melihat estimasi kadar glukosa darah.")

    with st.form("form_regresi"):
        col1, col2, col3 = st.columns(3)

        with col1:
            st.subheader(":material/person: Data Diri")
            age = st.slider("Umur (Tahun)", min_value=1, max_value=100, value=30)
            pregnancies = st.slider("Jumlah Kehamilan", min_value=0, max_value=20, value=0)
            bmi = st.slider("BMI (Indeks Massa Tubuh)", min_value=10.0, max_value=60.0, value=25.0, step=0.1)
            bp = st.slider("Tekanan Darah", min_value=50.0, max_value=200.0, value=120.0, step=1.0)
            hba1c = st.slider("HbA1c (%)", min_value=3.0, max_value=15.0, value=5.5, step=0.1)

        with col2:
            st.subheader(":material/biotech: Profil Lipid & Fisik")
            ldl = st.slider("Kadar LDL", min_value=0.0, max_value=300.0, value=100.0, step=1.0)
            hdl = st.slider("Kadar HDL", min_value=0.0, max_value=150.0, value=50.0, step=1.0)
            trig = st.slider("Triglycerides", min_value=0.0, max_value=500.0, value=150.0, step=1.0)
            wc = st.slider("Lingkar Pinggang (cm)", min_value=30.0, max_value=150.0, value=90.0, step=1.0)
            hc = st.slider("Lingkar Pinggul (cm)", min_value=30.0, max_value=150.0, value=100.0, step=1.0)
            whr = st.slider("Waist-to-Hip Ratio (WHR)", min_value=0.5, max_value=1.5, value=0.9, step=0.01)

        with col3:
            st.subheader(":material/medical_information: Riwayat Klinis")
            # Menggunakan select_slider untuk data kategorikal agar tampilannya tetap berupa slider
            fh_val = st.select_slider("Riwayat Keluarga Diabetes", options=["Tidak", "Ya"])
            dt_val = st.select_slider("Tipe Diet Terjaga", options=["Tidak", "Ya"])
            ht_val = st.select_slider("Hipertensi", options=["Tidak", "Ya"])
            meds_val = st.select_slider("Penggunaan Obat", options=["Tidak", "Ya"])
            out_val = st.select_slider("Status Diabetes Saat Ini", options=["Negatif", "Positif"])

            # Konversi nilai teks dari select_slider kembali ke angka 0/1 untuk model
            fh = 1 if fh_val == "Ya" else 0
            dt = 1 if dt_val == "Ya" else 0
            ht = 1 if ht_val == "Ya" else 0
            meds = 1 if meds_val == "Ya" else 0
            outcome = 1 if out_val == "Positif" else 0

        st.markdown("---")
        submit_button = st.form_submit_button(label=':material/analytics: Hitung Prediksi Glukosa')

        if submit_button:
            input_data = np.array([[age, pregnancies, bmi, bp, hba1c, ldl, hdl, trig, wc, hc, whr, fh, dt, ht, meds, outcome]])
            input_scaled = scaler_lr.transform(input_data)
            prediksi = lr_model.predict(input_scaled)

            st.success(f"### :material/science: Estimasi Kadar Glukosa Darah: **{prediksi[0]:.2f} mg/dL**")

            if prediksi[0] > 140:
                st.warning(":material/warning: Perhatian: Prediksi glukosa berada di atas ambang batas normal, disarankan pemeriksaan lebih lanjut.")

# ================= HALAMAN KLASIFIKASI DIABETES =================
elif page == ":material/stethoscope: Klasifikasi Diabetes":
    st.title(":material/stethoscope: Deteksi Dini Risiko Diabetes")
    st.markdown("Geser parameter pasien di bawah ini untuk melihat probabilitas risiko tinggi terkena diabetes.")

    with st.form("form_klasifikasi"):
        col1, col2, col3 = st.columns(3)

        with col1:
            st.subheader(":material/vital_signs: Data Klinis Utama")
            age = st.slider("Umur (Tahun)", min_value=1, max_value=100, value=35)
            pregnancies = st.slider("Jumlah Kehamilan", min_value=0, max_value=20, value=0)
            bmi = st.slider("BMI (Indeks Massa Tubuh)", min_value=10.0, max_value=60.0, value=25.0, step=0.1)
            glucose = st.slider("Kadar Glukosa", min_value=50.0, max_value=300.0, value=110.0, step=1.0)
            bp = st.slider("Tekanan Darah", min_value=50.0, max_value=200.0, value=120.0, step=1.0)
            hba1c = st.slider("HbA1c (%)", min_value=3.0, max_value=15.0, value=5.5, step=0.1)

        with col2:
            st.subheader(":material/biotech: Data Penunjang")
            ldl = st.slider("Kadar LDL", min_value=0.0, max_value=300.0, value=100.0, step=1.0)
            hdl = st.slider("Kadar HDL", min_value=0.0, max_value=150.0, value=50.0, step=1.0)
            trig = st.slider("Triglycerides", min_value=0.0, max_value=500.0, value=150.0, step=1.0)
            wc = st.slider("Lingkar Pinggang (cm)", min_value=30.0, max_value=150.0, value=90.0, step=1.0)
            hc = st.slider("Lingkar Pinggul (cm)", min_value=30.0, max_value=150.0, value=100.0, step=1.0)
            whr = st.slider("Waist-to-Hip Ratio (WHR)", min_value=0.5, max_value=1.5, value=0.9, step=0.01)

        with col3:
            st.subheader(":material/medical_information: Riwayat Klinis")
            fh_val = st.select_slider("Riwayat Keluarga Diabetes", options=["Tidak", "Ya"])
            dt_val = st.select_slider("Tipe Diet Terjaga", options=["Tidak", "Ya"])
            ht_val = st.select_slider("Hipertensi", options=["Tidak", "Ya"])
            meds_val = st.select_slider("Penggunaan Obat", options=["Tidak", "Ya"])

            # Konversi kembali ke 0 dan 1
            fh = 1 if fh_val == "Ya" else 0
            dt = 1 if dt_val == "Ya" else 0
            ht = 1 if ht_val == "Ya" else 0
            meds = 1 if meds_val == "Ya" else 0

        st.markdown("---")
        submit_button = st.form_submit_button(label=':material/search: Jalankan Analisis Risiko')

        if submit_button:
            with st.spinner("Memproses data pasien..."):
                input_data = np.array([[age, pregnancies, bmi, glucose, bp, hba1c, ldl, hdl, trig, wc, hc, whr, fh, dt, ht, meds]])
                input_scaled = scaler_nb.transform(input_data)
                hasil = nb_model.predict(input_scaled)

                if hasil[0] == 1:
                    st.error("### :material/emergency: HASIL: PASIEN BERISIKO TINGGI (DIABETES)")
                    st.write("Pasien menunjukkan indikasi kuat penyakit diabetes. Segera jadwalkan konsultasi lanjutan.")
                else:
                    st.success("### :material/check_circle: HASIL: PASIEN BERISIKO RENDAH (NORMAL)")
                    st.write("Pasien dalam kondisi aman dan tidak menunjukkan pola risiko diabetes.")
'''

with open('app.py', 'w') as f:
    f.write(streamlit_app_code)

print("Streamlit app code has been written to app.py")

!pip install -q streamlit
import streamlit as st
import pickle
import numpy as np

# Konfigurasi Halaman
st.set_page_config(
    page_title="Dashboard RS Sehat Sentosa",
    page_icon=":material/local_hospital:",
    layout="wide"
)

# Load model dan scaler
@st.cache_resource
def load_models():
    try:
        lr_model = pickle.load(open('linear_regression_model.pkl', 'rb'))
        scaler_lr = pickle.load(open('scaler_lr.pkl', 'rb'))
        nb_model = pickle.load(open('naive_bayes_model.pkl', 'rb'))
        scaler_nb = pickle.load(open('scaler_nb.pkl', 'rb'))
        return lr_model, scaler_lr, nb_model, scaler_nb
    except FileNotFoundError:
        st.error(":material/warning: File Model (.pkl) tidak ditemukan. Pastikan file berada di folder yang sama!")
        st.stop()

lr_model, scaler_lr, nb_model, scaler_nb = load_models()

# Sidebar Navigation
st.sidebar.title(":material/dashboard: Navigasi Utama")
st.sidebar.markdown("Silakan pilih menu layanan:")
page = st.sidebar.radio("Menu", [
    ":material/home: Beranda",
    ":material/water_drop: Prediksi Glukosa (Regresi)",
    ":material/stethoscope: Klasifikasi Diabetes"
])
st.sidebar.markdown("---")
st.sidebar.info(":material/info: Dashboard analitik ini dirancang khusus untuk tim medis RS Sehat Sentosa guna deteksi dini risiko diabetes.")

# ================= BERANDA =================
if page == ":material/home: Beranda":
    st.title(":material/local_hospital: Sistem Cerdas Deteksi Dini Diabetes")
    st.markdown("### Selamat Datang di Dashboard Rumah Sakit Sehat Sentosa")
    st.write("""
    Aplikasi ini ditenagai oleh model **Machine Learning** terintegrasi untuk membantu tenaga medis:

    1. **Prediksi Glukosa:** Mengestimasi kadar glukosa darah pasien secara kuantitatif berdasarkan profil klinis (Algoritma *Linear Regression*).
    2. **Klasifikasi Risiko:** Memprediksi apakah pasien berisiko tinggi terkena diabetes atau tidak (Algoritma *Naive Bayes + SMOTE*).

    :material/arrow_back: *Silakan pilih menu pada panel navigasi di sebelah kiri untuk mulai menggunakan fitur.*
    """)

# ================= HALAMAN PREDIKSI GLUKOSA =================
elif page == ":material/water_drop: Prediksi Glukosa (Regresi)":
    st.title(":material/water_drop: Prediksi Kadar Glukosa Darah")
    st.markdown("Geser slider di bawah ini untuk memasukkan data klinis pasien dan melihat estimasi kadar glukosa darah.")

    with st.form("form_regresi"):
        col1, col2, col3 = st.columns(3)

        with col1:
            st.subheader(":material/person: Data Diri")
            age = st.slider("Umur (Tahun)", min_value=1, max_value=100, value=30)
            pregnancies = st.slider("Jumlah Kehamilan", min_value=0, max_value=20, value=0)
            bmi = st.slider("BMI (Indeks Massa Tubuh)", min_value=10.0, max_value=60.0, value=25.0, step=0.1)
            bp = st.slider("Tekanan Darah", min_value=50.0, max_value=200.0, value=120.0, step=1.0)
            hba1c = st.slider("HbA1c (%)", min_value=3.0, max_value=15.0, value=5.5, step=0.1)

        with col2:
            st.subheader(":material/biotech: Profil Lipid & Fisik")
            ldl = st.slider("Kadar LDL", min_value=0.0, max_value=300.0, value=100.0, step=1.0)
            hdl = st.slider("Kadar HDL", min_value=0.0, max_value=150.0, value=50.0, step=1.0)
            trig = st.slider("Triglycerides", min_value=0.0, max_value=500.0, value=150.0, step=1.0)
            wc = st.slider("Lingkar Pinggang (cm)", min_value=30.0, max_value=150.0, value=90.0, step=1.0)
            hc = st.slider("Lingkar Pinggul (cm)", min_value=30.0, max_value=150.0, value=100.0, step=1.0)
            whr = st.slider("Waist-to-Hip Ratio (WHR)", min_value=0.5, max_value=1.5, value=0.9, step=0.01)

        with col3:
            st.subheader(":material/medical_information: Riwayat Klinis")
            # Menggunakan select_slider untuk data kategorikal agar tampilannya tetap berupa slider
            fh_val = st.select_slider("Riwayat Keluarga Diabetes", options=["Tidak", "Ya"])
            dt_val = st.select_slider("Tipe Diet Terjaga", options=["Tidak", "Ya"])
            ht_val = st.select_slider("Hipertensi", options=["Tidak", "Ya"])
            meds_val = st.select_slider("Penggunaan Obat", options=["Tidak", "Ya"])
            out_val = st.select_slider("Status Diabetes Saat Ini", options=["Negatif", "Positif"])

            # Konversi nilai teks dari select_slider kembali ke angka 0/1 untuk model
            fh = 1 if fh_val == "Ya" else 0
            dt = 1 if dt_val == "Ya" else 0
            ht = 1 if ht_val == "Ya" else 0
            meds = 1 if meds_val == "Ya" else 0
            outcome = 1 if out_val == "Positif" else 0

        st.markdown("---")
        submit_button = st.form_submit_button(label=':material/analytics: Hitung Prediksi Glukosa')

        if submit_button:
            input_data = np.array([[age, pregnancies, bmi, bp, hba1c, ldl, hdl, trig, wc, hc, whr, fh, dt, ht, meds, outcome]])
            input_scaled = scaler_lr.transform(input_data)
            prediksi = lr_model.predict(input_scaled)

            st.success(f"### :material/science: Estimasi Kadar Glukosa Darah: **{prediksi[0]:.2f} mg/dL**")

            if prediksi[0] > 140:
                st.warning(":material/warning: Perhatian: Prediksi glukosa berada di atas ambang batas normal, disarankan pemeriksaan lebih lanjut.")

# ================= HALAMAN KLASIFIKASI DIABETES =================
elif page == ":material/stethoscope: Klasifikasi Diabetes":
    st.title(":material/stethoscope: Deteksi Dini Risiko Diabetes")
    st.markdown("Geser parameter pasien di bawah ini untuk melihat probabilitas risiko tinggi terkena diabetes.")

    with st.form("form_klasifikasi"):
        col1, col2, col3 = st.columns(3)

        with col1:
            st.subheader(":material/vital_signs: Data Klinis Utama")
            age = st.slider("Umur (Tahun)", min_value=1, max_value=100, value=35)
            pregnancies = st.slider("Jumlah Kehamilan", min_value=0, max_value=20, value=0)
            bmi = st.slider("BMI (Indeks Massa Tubuh)", min_value=10.0, max_value=60.0, value=25.0, step=0.1)
            glucose = st.slider("Kadar Glukosa", min_value=50.0, max_value=300.0, value=110.0, step=1.0)
            bp = st.slider("Tekanan Darah", min_value=50.0, max_value=200.0, value=120.0, step=1.0)
            hba1c = st.slider("HbA1c (%)", min_value=3.0, max_value=15.0, value=5.5, step=0.1)

        with col2:
            st.subheader(":material/biotech: Data Penunjang")
            ldl = st.slider("Kadar LDL", min_value=0.0, max_value=300.0, value=100.0, step=1.0)
            hdl = st.slider("Kadar HDL", min_value=0.0, max_value=150.0, value=50.0, step=1.0)
            trig = st.slider("Triglycerides", min_value=0.0, max_value=500.0, value=150.0, step=1.0)
            wc = st.slider("Lingkar Pinggang (cm)", min_value=30.0, max_value=150.0, value=90.0, step=1.0)
            hc = st.slider("Lingkar Pinggul (cm)", min_value=30.0, max_value=150.0, value=100.0, step=1.0)
            whr = st.slider("Waist-to-Hip Ratio (WHR)", min_value=0.5, max_value=1.5, value=0.9, step=0.01)

        with col3:
            st.subheader(":material/medical_information: Riwayat Klinis")
            fh_val = st.select_slider("Riwayat Keluarga Diabetes", options=["Tidak", "Ya"])
            dt_val = st.select_slider("Tipe Diet Terjaga", options=["Tidak", "Ya"])
            ht_val = st.select_slider("Hipertensi", options=["Tidak", "Ya"])
            meds_val = st.select_slider("Penggunaan Obat", options=["Tidak", "Ya"])

            # Konversi kembali ke 0 dan 1
            fh = 1 if fh_val == "Ya" else 0
            dt = 1 if dt_val == "Ya" else 0
            ht = 1 if ht_val == "Ya" else 0
            meds = 1 if meds_val == "Ya" else 0

        st.markdown("---")
        submit_button = st.form_submit_button(label=':material/search: Jalankan Analisis Risiko')

        if submit_button:
            with st.spinner("Memproses data pasien..."):
                input_data = np.array([[age, pregnancies, bmi, glucose, bp, hba1c, ldl, hdl, trig, wc, hc, whr, fh, dt, ht, meds]])
                input_scaled = scaler_nb.transform(input_data)
                hasil = nb_model.predict(input_scaled)

                if hasil[0] == 1:
                    st.error("### :material/emergency: HASIL: PASIEN BERISIKO TINGGI (DIABETES)")
                    st.write("Pasien menunjukkan indikasi kuat penyakit diabetes. Segera jadwalkan konsultasi lanjutan.")
                else:
                    st.success("### :material/check_circle: HASIL: PASIEN BERISIKO RENDAH (NORMAL)")
                    st.write("Pasien dalam kondisi aman dan tidak menunjukkan pola risiko diabetes.")

!pip install -q pyngrok

import os
import time
from pyngrok import ngrok

# 1. Matikan sesi ngrok sebelumnya agar tidak error port / nyangkut
ngrok.kill()
os.system("killall -9 ngrok")

# 2. Masukkan Token Auth Ngrok (GANTI DENGAN TOKEN ASLI DARI DASHBOARD KAMU)
# Contoh: NGROK_TOKEN = "2aXyZ123abcd..."
NGROK_TOKEN = "3EGFWNiiH82ARVqcdsGnc6pesmw_2ZJ4U3xSabniYwqXC2GwD"
ngrok.set_auth_token(NGROK_TOKEN)

# 3. Jalankan Streamlit di background (menyembunyikan output terminal)
os.system("nohup streamlit run app.py >/dev/null 2>&1 &")

# 4. Beri jeda 5 detik agar server Streamlit siap sebelum tunnel dibuat
time.sleep(5)

# 5. Buat public URL
public_url = ngrok.connect(8501).public_url
print(f"✅ Dashboard berhasil di-deploy!")
print(f"👉 Klik link berikut untuk membuka: {public_url}")

